### ISSUE TITLE
Include ELKI

### ISSUE THREAD

**Issue by kno10** [v-m/ml-perf#3]
The clustering implementations in ELKI try to be very careful and close to the original sources.

When there are multiple known variants (e.g., k-means) we try to implement all of them.

Beware that you cannot trust the "sum of squares" reported by the various toolkits, because of numerical differences. Some tools compute them in a numerical unreliable way (c.f., Schubert, E., & Gertz, M. (2018, July). Numerically stable parallel computation of (co-) variance. In Proceedings of the 30th International Conference on Scientific and Statistical Database Management (p. 10). ACM. - this also applies to using the dot product to compute distances as used in sklearn; and we show there is a numerical instability in some GMM implementations)

Also beware that toolkits may differ in their implementation of ARI and such measures, in particular when it comes to handling noise (i.e., DBSCAN) where this index is problematic anyway. ELKI has different noise handling strategies for evaluating such clusterings.

**Comment by v-m** [comment]
I don't work actively anymore on this tool.
If you feel to improve this tool, I can review any PRs but that's the best I can do with my current schedule 🤷‍♂
